### PR TITLE
Restored 'molecular weight' as Text

### PR DESCRIPTION
**Pull request by egonw**
Closes https://github.com/BioSchemas/specifications/issues/347

### CODE REVIEW

**Review by AlasdairGray — CHANGES_REQUESTED** [review]
Shouldn't the description talk about g/mol as per the discussion in issue https://github.com/BioSchemas/specifications/issues/347 rather than leaving it plainly as a mass with a unit of g?

**Comment by egonw** [comment]
I'll update this patch to use `Number` and add a good example.

**Comment by egonw** [comment]
@AlasdairGray, I'm confused... but I think I'll do this. The range should be `Number` (where `amu` is implied) and `QuantitativeValue`. Does that sound right? Two examples:

```json
"molecularWeight" : { 
            "@type" : "QuantitativeValue",
            "value" : "12",
            "unitText" : "amu"
  }
```

There does not seem to be a UN/CEFACT Common Codes for `Da` nor `amu`.

Or, as simply number (so, implying amu):

```json
"molecularWeight" : "12"
```

**Comment by AlasdairGray** [comment]
I think that Number can be used in very messy ways, see [elevation](https://schema.org/elevation) where they talk of including the units with the value.
>The elevation of a location (WGS 84). Values may be of the form 'NUMBER UNITOFMEASUREMENT' (e.g., '1,000 m', '3,200 ft') while numbers alone should be assumed to be a value in meters.

Perhaps we should combine both, i.e. QuantativeValue approach and then the elevation approach as well.

**Comment by egonw** [comment]
@AlasdairGray, the text already had an example use of `Text`. Please see the two news patches.

**Review by AlasdairGray — APPROVED** [review]
That's great. Avoids any confusion of using grams to represent molecular weight.

**Pull request merged**
