### PR TITLE
Address issues around hasRepresentation/hasSequence in Issue 321

### PR DESCRIPTION
**Pull request by AlasdairGray**
In this pull request I have renamed `hasSequence` to `hasBioPolymerSequence` and updated the definition. This makes clearer the distinction between these properties and how they would be used.

I have also declared 3 properties on `MolecularEntity` as sub-properties of `hasRepresentation`.

This is as per the discussion in https://github.com/BioSchemas/specifications/issues/321

### CODE REVIEW

**Review by egonw — APPROVED** [review]
I have seen the three suggested `rdfs:subPropertyOf` additions and approve.

**Review by ljgarcia — COMMENTED** [review]
So, 
* hasBioPolymerSequence extends hasRepresentation, 
* Gene includes property hasBioPolymerSequence but 
* Protein does not include property hasBioPolymerSequence. 

Am I undestanding this correctly?

**Comment by AlasdairGray** [comment]
Yes except that hasBioPolymerSequence is defined for both gene and protein.
________________________________

**Comment by AlasdairGray** [comment]
@ljgarcia are you happy with renaming and revised definition of `hasSequence` to `hasBioPolymerSequence`? It is defined for use on both Gene and Protein.

**Comment by ljgarcia** [comment]
Looks good, both Gene and Protein appear as domains for the property on the Gene file.

**Review by ljgarcia — APPROVED** [review]

**Pull request merged**
